### ISSUE TITLE
[REQ] Multi-device management

### ISSUE THREAD

**Issue by YexuanXiao** [timschneeb/GalaxyBudsClient#214]
I have both Buds Pro and Buds+ and both will be connected to my PC. Currently, when I switch from one pair of headphones to the other, I need to re-pair the devices, which is slightly tedious. I would like the software to be able to connect to the new device quickly.

**Comment by ThePBone** [comment]
I had this on my to-do list for quite some time; however, this would require me to rewrite large chunks of the code so I didn't find any time to work on it yet. This will get added eventually, I don't have an ETA at the moment though.

**Comment by timschneeb** [comment]
Multi-device support has been added in v5.0.0: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0
