### ISSUE TITLE
[REQ] Play/Pause on Linux

### ISSUE THREAD

**Issue by alba4k** [timschneeb/GalaxyBudsClient#365]
**Is your feature request related to a problem? Please describe.**
_It would be nice if the "automatically play/pause music when removing earbuds" feature would work on Linux_

**Describe the solution you'd like**
_This would be fairly easy to achieve by simulating a press of `XF86AudioPlay` or `XF86AudioPause`_

**Describe alternatives you've considered**
_This could also be achieved by running `playerctl play-pause`, which would require playerctl to be installer (it would usually already be)._

**Comment by salihefee** [comment]
Fixed in #584

**Comment by alba4k** [comment]
@salihefee isn't that pr just for pausing?

**Comment by salihefee** [comment]
The resuming feature is already there?

**Comment by alba4k** [comment]
never worked for me on Linux

might test again tomorrow tho, I guess

**Comment by timschneeb** [comment]
The resuming feature uses the Mpris D-Bus API for controlling playback, so it only works with players that have Mpris support. It works for me with Firefox on Linux at least (btw, I'm using the KDE plasma browser integration addon which exposes a mpris player, if that's relevant).

By the way, to verify that the 'resume' request gets actually triggered, you can monitor the logs with
```
tail -f ~/.local/share/GalaxyBudsClient/application.log
```
and look for a line containing `[DBG] Linux.MediaKeyRemote: Play request sent` when you put your earbuds back in.

**Comment by alba4k** [comment]
Huh, yeah laying does work, you're right. I always wrongfully assumed the audio would pause too (as it does on android too, since I thought that the earbud itself was sending a pause event whenever it stopped being worn)
