### ISSUE TITLE
Addition of title at Touchpad section

### ISSUE THREAD

**Issue by creatorGod003** [timschneeb/GalaxyBudsClient#435]
I have come across application. It's great to use with my Samsung galaxy buds2pro. But I am thinking of a feature to improve User Experience of users.
In touchpad section of your application configuration for left and right action only works when advance touchpad gestures are on. If users use your application for first time, they will not get clarity that these options only works when customization settings are on. If there is some title or something, it will good. 

Hope so I am able to convey my thought to you.

**Comment by timschneeb** [comment]
This has been fixed in the latest version: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0
