### ISSUE TITLE
[AUR] PKGBUILD fails

### ISSUE THREAD

**Issue by JarneDel** [timschneeb/GalaxyBudsClient#486]
I'm new to maintaining packages on arch, so don't know if opening an issue here is relevant, but either way:
For the new galaxybudsclient-git version of the PKGBUILD, the icon was renamed, and needs to be updated in there.
change
` install -Dm644 "${srcdir}/${pkgname}/GalaxyBudsClient/Resources/icon_white.png" "${pkgdir}/usr/share/pixmaps/${_pkgname}.png"`

to
  `install -Dm644 "${srcdir}/${pkgname}/GalaxyBudsClient/Resources/icon.png" "${pkgdir}/usr/share/pixmaps/${_pkgname}.png"`

**Comment by EmKaCe** [comment]
Hi,

sorry for the very late reply, life has been a little busy and I do not receive emails on this repo. I just enabled notifications for this repo too.

The mentioned issue should be fixed now with the [latest commit in the AUR](https://aur.archlinux.org/cgit/aur.git/commit/?h=galaxybudsclient-git&id=7b40988181d7ef9f2bb29864a7b928c8a90ee431)
