### ISSUE TITLE
[BUG] The main window doesn't show up

### ISSUE THREAD

**Issue by kwon0408** [timschneeb/GalaxyBudsClient#489]
**Describe the bug**  
The main window doesn't show up, and the tray icon makes no response when clicked, double clicked or right clicked. The tooltip shows properly when hovered on.

**To Reproduce**  
- Click, double click or right click the tray icon.

**Expected behavior**  
The main window (or maybe a context menu) should show up.

**Screenshots**  
N/A

**Desktop (please complete the following information):**  
 - OS: Windows 11 23H2 64bit, OS Build number 22631.3296, default system language: Korean
 
 - Application version: 4.6.0

**Additional context**  
N/A

**Log files**  
[application.log](https://github.com/timschneeb/GalaxyBudsClient/files/15071716/application.log)
[application.log](https://github.com/timschneeb/GalaxyBudsClient/files/15071698/application.log) (after reinstall)

**Comment by timschneeb** [comment]
Fixed in the latest version: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0
