### ISSUE TITLE
[BUG] Buds 2 Pro not detected on MacOS

### ISSUE THREAD

**Issue by mwisnicki** [timschneeb/GalaxyBudsClient#493]
**Describe the bug**  
App did not find Buds 2 but manual pairing worked.

**To Reproduce**  
1. Unregister device from the app
2. Ensure buds are connected to Mac
3. Attempt to register

**Expected behavior**  
Device should be shown in the list of detected devices.

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: MacOS Sonoma 14.4.1 / arm
 - Application version: 4.6.0.0

**Additional context**  
![image](https://github.com/timschneeb/GalaxyBudsClient/assets/96032/d423d515-4353-4f3a-9cf6-f97febbacdc8)

**Log files**  
[application.log](https://github.com/timschneeb/GalaxyBudsClient/files/15178346/application.log)

BTW the path on mac is `~/Library/Application Support/GalaxyBudsClient`, the bug template should be updated.

**Comment by timschneeb** [comment]
This was caused by the personalized device names since I used the name to detect the model until now.
The latest release can now more reliably detect models using Bluetooth metadata. It's already implemented in the Windows and Linux backend; macOS is work in progress.
