### ISSUE TITLE
[BUG] Battery status in main window takes few seconds to show and sometimes flickers

### ISSUE THREAD

**Issue by mwisnicki** [timschneeb/GalaxyBudsClient#494]
**Describe the bug**  
If I open the app and navigate to any screen then navigate back to main window it takes about 3s for battery status to show up.

Additionally in some cases the battery status will disappear while on main screen only to reappear second later.
I also have bluetooth address sometimes disappearing in System information screen for a second.

**To Reproduce**  
1. Open App
2. Go to System
3. Go back

**Expected behavior**  
The battery status is cached for reasonable time and always visible when app is open (unless app couldn't obtain it).

**Screenshots**  
![image](https://github.com/timschneeb/GalaxyBudsClient/assets/96032/c6695853-1179-4683-8d86-4ae9d1fa7e6d)
![image](https://github.com/timschneeb/GalaxyBudsClient/assets/96032/3ca32e76-c39c-4459-924c-c3697835b8a0)

**Desktop (please complete the following information):**  
OS: MacOS Sonoma 14.4.1 / arm
Application version: 4.6.0.0

**Additional context**  

**Log files**  
See https://github.com/timschneeb/GalaxyBudsClient/issues/493

**Comment by wpzdm** [comment]
I also observed this on macOS 13 and app ver 4.6.

**Comment by d-avery** [comment]
Issue is also present on Arch Linux 6.9.3-arch1-1 and app version 4.6.0.

**Comment by timschneeb** [comment]
Fixed in the latest version: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0
