### ISSUE TITLE
[REQ] Buds2 pro touchpad

### ISSUE THREAD

**Issue by wpzdm** [timschneeb/GalaxyBudsClient#497]
Hi, thanks for this app the works great on Mac!

**Is your feature request related to a problem? Please describe.**

I read the official document (https://www.samsung.com/us/support/answer/ANS00078137/). According to it, we have commands associated with 1/2/3 taps and we can customize each of the gestures using the official wearable app.
But on your app, I can find only Left/right action; and they are the "tap and hold" gesture as far as I tested. Could we set other gesture on your app?

2 and 3 tap-gestures do not work for me. Is it because I don't use the official app?

The "lock touchpad" feature does not work for me; tap still pauses the music even if it is on.

**Describe the solution you'd like**
NA for now.

**Describe alternatives you've considered**
NA for now.

**Additional context**
I am new to galaxy buds and I cannot connect it to my very old Android phone. So please bear with my newbie questions. Most of them would not lead to real feature requests I guess.

**Comment by timschneeb** [comment]
This should be fixed in the latest release: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0
