### ISSUE TITLE
Firmware informations are wrong (not updated with firmware update)[BUG] 

### ISSUE THREAD

**Issue by MRKSC** [timschneeb/GalaxyBudsClient#499]
**Describe the bug**  
Firmware informations are wrong (not updated with firmware update). In phone app and in manager.

**To Reproduce**  
present

**Expected behavior**  
to see actual firmware installed

**Screenshots**  

**Desktop (please complete the following information):**  
Androind 13
windows 11

**Additional context**  

**Log files**  
In most cases if you have a bug, log file will be required - it is located at ```%localappdata%\GalaxyBudsClient\application.log```

**Comment by timschneeb** [comment]
This indicates that the earbuds rejected the update file. It's hard to say what caused this. 

There's a good chance that the latest version fixes this; the majority of this app has been completely rewritten: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0
