### ISSUE TITLE
[CRSH] Launch fails on Mac m1 laptop using arm64 pkg

### ISSUE THREAD

**Issue by tomleo** [timschneeb/GalaxyBudsClient#500]
**Shortly describe what were you doing before crash**
Opening the program

**Include event files here**

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000001ae
Exception Codes:       0x0000000000000001, 0x00000000000001ae
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [96932]

VM Region Info: 0x1ae is not in any region.  Bytes before following region: 105553518919250
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)
```

**Desktop (please complete the following information):**
 - OS: MacBookPro18,3, BootROM 7459.141.1, proc 8:6:2 processors, 32 GB, SMC (macOS Monterey 12.6)
 - Application version: 4.6.0.0

**Additional context**
Installed the arm64 pkg on an m1 laptop

**Comment by nift4** [comment]
does this still happen with https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0 ?

**Comment by tomleo** [comment]
> does this still happen with https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0 ?

Latest release seems to work!

(Aside: I needed to manually select the ear-buds, it didn't automatically find them)

**Comment by nift4** [comment]
Maybe it's an issue or incompatibility with Monterey, I only tested with Sonoma /shrug
