### ISSUE TITLE
Window and text are tiny

### ISSUE THREAD

**Issue by rw-bowman** [timschneeb/GalaxyBudsClient#501]
**Describe the bug**  
Window and text are tiny on 4k screen and nothing is resizable
**To Reproduce**  

Steps to reproduce the behavior:Launch app

**Expected behavior**
Window should be resizable or just bigger

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: Kubuntu 24.04
 - Application version: 4.6.0.0

**Additional context**  

**Log files**  
In most cases if you have a bug, log file will be required - it is located at ```%localappdata%\GalaxyBudsClient\application.log```

**Comment by timschneeb** [comment]
See this issue for a workaround: https://github.com/timschneeb/GalaxyBudsClient/issues/311#issuecomment-1937246165
