### ISSUE TITLE
Noise Filter for Galaxy buds mic 

### ISSUE THREAD

**Issue by WildFire212** [timschneeb/GalaxyBudsClient#508]
Hello, galaxy buds mic quality is terrible, is it possible to add a noise suppression filter? 

### I had raised a question regarding this in the discussions https://github.com/timschneeb/GalaxyBudsClient/discussions/505

<div type='discussions-op-text'>

<sup>Originally posted by **WildFire212** June  3, 2024</sup>
Hello raising the Q&A for some questions i have regarding the galaxy buds 2 mic. 

Galaxy buds 2 has a terrible mic quality and picks up everything from the background but not your voice. 
I have tried downgrading my firmware with no luck. 

I am currently thinking of 2 possible solutions, 
1. Adding a noise filter to the galaxy buds client (if it processes the mic data in any way) 
2. Somehow adding that noise filter to the buds firmware itself. </div>

**Comment by timschneeb** [comment]
Hi,

Patching the firmware would be very hard, especially for something complex like audio signal processing.
This app is only designed to read/write configuration from the earbuds, it cannot intercept audio data.

As an alternative, you could use something like [EqualizerAPO](https://sourceforge.net/projects/equalizerapo/) on Windows or [EasyEffects](https://github.com/wwmm/easyeffects) on Linux to apply audio filters on the microphone input.
