### ISSUE TITLE
[BUG] Abnormal CPU usage

### ISSUE THREAD

**Issue by RootOperator** [timschneeb/GalaxyBudsClient#515]
**Describe the bug**  
Idle in background uses about 8% cpu which doesn't sound right (not sure what the old version had) but when disconnecting and reconnecting my buds 2 pro while the application is running the CPU usages goes up to 16% and stays there until you completely close and re open it again

**To Reproduce**  
Run application in background. disconnect earbuds and reconnect.

**Expected behavior**  
No permanent doubling of the CPU usage.

**Screenshots**  
![image](https://github.com/timschneeb/GalaxyBudsClient/assets/20143055/66daae0b-80c7-457a-b871-79fe8308c7f9)

**Desktop (please complete the following information):**  
 - OS: Arch linux 6.9.4-arch1-1
 - Application version: 5.0.0.0+e9073e1b081e2db2e17c935c4bffe912eafacdd4

**Additional context**  

**Log files**  
[application.log](https://github.com/user-attachments/files/15898770/application.log)

**Comment by mahmutsezai** [comment]
Same behaviour on arch 6.9.5.
Cpu usage goes to %100 as soon as application is open.
![Screenshot from 2024-06-20 23-58-06](https://github.com/timschneeb/GalaxyBudsClient/assets/82783313/12971dd8-9d1f-4b43-97f6-0bc6e28bce79)

**Comment by timschneeb** [comment]
I fixed this recently, but I haven't released a new stable release for it yet.
You can download a build with the fix here for now: https://github.com/timschneeb/GalaxyBudsClient/actions/runs/9539521694

**Comment by d-avery** [comment]
Also have this issue on Arch. Good to know there's a fix!

**Comment by timschneeb** [comment]
The fix has been released in v5.0.1: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.1

**Comment by dougmeek** [comment]
I've been running 5.0.1 on Linux for a couple days and the 100% CPU bug does not seem to be fixed. Keeps one of my cores pegged constantly. If you would like debug data, please let me know what you'd like to see.

**Comment by dougmeek** [comment]
Screenshot attached:

![Screenshot_20240701_153854](https://github.com/timschneeb/GalaxyBudsClient/assets/30700062/bd97e3e6-298d-4dee-b0ba-5845b437b5f1)

**Comment by timschneeb** [comment]
I found a deadlock in one of the UI libraries I'm using. Downgrading it (commit ab5f349) appears to have fixed the 100% CPU usage bug on my system. I'll have to test it for a while to make sure it's actually fixed, though.

Binaries with the fix can be downloaded here for now: https://github.com/timschneeb/GalaxyBudsClient/actions/runs/9900010544

**Comment by timschneeb** [comment]
Fixed by https://github.com/TolikPylypchuk/SharpHook/issues/112 and b3c741b

**Comment by dougmeek** [comment]
Thanks for looking into this @timschneeb. I'll give it a test drive later today. Since I'm running Nvidia, I haven't tested this with Wayland yet, but hopefully this fixes it for X11.
