### ISSUE TITLE
[REQ] Update the winget package for galaxybuds

### ISSUE THREAD

**Issue by prakharb5** [timschneeb/GalaxyBudsClient#522]
**Is your feature request related to a problem? Please describe.**

Please update the app package on winget, it is still using 4.6.0 even though 5.0.1 has been released

created an issue on winget-pkgs: https://github.com/microsoft/winget-pkgs/issues/161127

**Comment by prakharb5** [comment]
winget is having issues detecting the installed version of the package :/
https://github.com/timschneeb/GalaxyBudsClient/issues/431#issuecomment-2205270535

![image](https://github.com/timschneeb/GalaxyBudsClient/assets/51435948/819131d8-cf2f-4096-9ab9-22a284312db5)

**Comment by Dragon1573** [comment]
![image](https://github.com/timschneeb/GalaxyBudsClient/assets/49941141/932bba55-c895-4480-baab-893e0c6c97bd)

This package does not write `DisplayVersion` into _Windows Registry_. `winget.exe` does not able to detect it. 😞

**Comment by timschneeb** [comment]
> This package does not write `DisplayVersion` into _Windows Registry_. 

This will be fixed in the next version. A while back, my CI build script stopped setting the correct version information.
(Fixed in commit 85b88b58a8e203d37ce5ec6f626ed1b6b06d63e6)

**Comment by timschneeb** [comment]
v5.1.0 with the fix has been released. The update will be available soon in the WinGet repo too once this PR is merged: https://github.com/microsoft/winget-pkgs/pull/163373

> Are you willing to integrate [WinGet Releaser v2](https://github.com/marketplace/actions/winget-releaser) to your workflow?

Yes, I've added it now. Thanks for the hint :+1:

**Comment by 1404813005** [comment]
thank you
