### ISSUE TITLE
[BUG] Maximum transfer unit: 650 bytes

### ISSUE THREAD

**Issue by xopherKPMG** [timschneeb/GalaxyBudsClient#524]
**Describe the bug**  
I am trying to downgrade the firmware for my Galaxy Buds2 pro, following the advice here:
https://www.reddit.com/r/galaxybuds/comments/1cwh2ba/galaxy_buds2_pro_sound_quality_and_anc/
I am encountering an issue when uploading the firmware to the earbuds. It seems the maximum transfer unit for data segments is 650 bytes. This makes the firmware upload extremely slow. Worse, sometimes there is a random interruption with the connection, forcing me to start over. I am unable to find a way to fix this. It is frustrating since noone else is experiencing this issue. For most people they seem to be able to upload firmware in five minutes.

**To Reproduce**  

    Download and install galaxy buds client 4.5.2:

https://github.com/timschneeb/GalaxyBudsClient/releases/tag/4.5.2

2. Check SM -R510 galaxy buds 2 pro versions ..in that june version where it ends with WF4, download that from here:

https://github.com/timschneeb/galaxy-buds-firmware-archive?tab=readme-ov-file

3. Pair your buds to your pc, put your buds in the case and leave it open.

4. Open the galaxy buds client unofficial.. click next click galaxy buds2 pro .. click view information and click install firmware update.. click advanced and select the downloaded file WF4 ..

5. Selecting the file WF4 will ask u to downgrade and click Yes and it will start downgrading and after finishes wait for a minute and then check the version it will show wf4.

firmware upload will be extremely slow

**Expected behavior**  
I expect the firmware upload to only take a few minutes

**Screenshots**  
![image](https://github.com/timschneeb/GalaxyBudsClient/assets/161435998/03aa1873-4448-4fcf-b73d-963082a00493)

**Desktop (please complete the following information):**  
 - OS: Ubuntu 23.10 [x86-64] Linux 6.5.0-42-generic
 
 - Application version: 4.52

**Comment by timschneeb** [comment]
The maximum transfer unit of 650 bytes is normal. That's the case for all earbud models. 

Please update the application to 5.0.0 or later, that will significantly speed the transfer process up.
Older versions like 4.5.2 on Linux had major performance issues when transferring firmware updates.
