### ISSUE TITLE
Flatpak Package update to latest version

### ISSUE THREAD

**Issue by Sanjay-Khadka** [timschneeb/GalaxyBudsClient#525]
Thank you for creating this amazing project,  It works great. when can we expect a flatpak package upgrade from version 4.6.0 that reflects the new changes. I tried building the flatpak package by myself and failed to do so, I'd be a great help if this flatpak package for this was upgraded to version 5.

**Comment by Sanjay-Khadka** [comment]
Hi, @timschneeb i am able to update to the latest package. Thank you!

**Comment by alirezarm78** [comment]
Hey there.
Is there any update on flatpak?
I'm not able to update from flatpak.

**Comment by dominiksr** [comment]
@timschneeb The latest version is from 8 months ago. It would be great if it could be updated.

**Comment by dominiksr** [comment]
Thank you :D
