### ISSUE TITLE
[BUG]  UI Doesn't look the same as picture in Github examples

### ISSUE THREAD

**Issue by xii69** [timschneeb/GalaxyBudsClient#526]
**Describe the bug**  
Just installed it using Flatpak, doesn't look same as the picture provided in github at all, didn't found an option for changing the UI

**To Reproduce**  
Install the app using Flatpak on Ubuntu

**Expected behavior**  
Should have a way better UI like the picture

**Screenshots**  
![image](https://github.com/user-attachments/assets/650839e5-df51-499d-8c67-d6b8b3034a09)

**Desktop (please complete the following information):**  
 - OS: Linux (Ubuntu 24.04 / KDE with SDDM)
 - Application version: [5.0.1](https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.1)

**Comment by timschneeb** [comment]
You're running version v4.6.0.
Flathub has not yet received the v5.0.0 and v5.0.1 updates.

I'm not the maintainer of the Flatpak package and I don't know how to update it properly, so I can't give you an ETA when it is ready. I might look into getting it updated myself at some point, but I don't have much spare time atm.

**Comment by timschneeb** [comment]
I've just published a new flatpak update. It might take a few hours until it appears on FlatHub though.

**Comment by xii69** [comment]
> I've just published a new flatpak update. It might take a few hours until it appears on FlatHub though.

Nice, so i just have to reinstall it through flatpak ig
