### ISSUE TITLE
[BUG] Firmware update wrongly detects device mismatch

### ISSUE THREAD

**Issue by laust0rm** [timschneeb/GalaxyBudsClient#533]
**Describe the bug**  
I wanted to update the firmware on my Buds2 Pro, and the list only contained Buds2 firmware. When I wanted to load a custom firmware binary, I got the message "Device model mismatch detected! [...]", even though the program detects my buds as Buds2 Pro. (in the main screen)

**To Reproduce**  
My phone says the firmware is R510XXU0AVK3, which is what I originally flashed, but galaxybudsclient says R177XXU0AVK3. I don't know what caused this, but I think this is what caused the behaviour.

**Expected behavior**  
Expected gbc to list B2P firmware/allow the custom bin.

**Screenshots**  
![image](https://github.com/user-attachments/assets/9b6674a3-e0e8-43e1-aee8-1e6aba0cb0a0)
![img](https://github.com/user-attachments/assets/ca06c547-4ea5-4b1c-8124-efcd63d4d347)

**Desktop (please complete the following information):**  
 - OS: 
Windows 11 Home 64bit 22631.3880
 
 - Application version: 
5.1.0.0

**Log files**  
[application.log](https://github.com/user-attachments/files/16398793/application.log)

**Comment by YexuanXiao** [comment]
Does this issue still exist in the latest version? I own Buds2Pro but it won't reproduce on my device.

**Comment by timschneeb** [comment]
> I wanted to update the firmware on my Buds2 Pro, and the list only contained Buds2 firmware. When I wanted to load a custom firmware binary, I got the message "Device model mismatch detected! [...]", even though the program detects my buds as Buds2 Pro. (in the main screen)

Old versions of GalaxyBudsClient had an issue that wrongly identified the Galaxy Buds2 Pro as a pair of Galaxy Buds2 instead during the setup. You're already using a new version with the bugfix, but the incorrect model value is still in the config. 

To fix this, just unregister the device and then re-add it. This time, it will be correctly identified as Buds2 Pro and the error will vanish.

**Comment by Viktor-2b** [comment]
Completely the same situation here, with the latest version 5.1
Unregistering and then re-adding doesn't work
