### ISSUE TITLE
[BUG] Case Software version and serial number position reversed

### ISSUE THREAD

**Issue by backryun** [timschneeb/GalaxyBudsClient#535]
**Describe the bug**  
Case Software version and serial number position reversed. this is Buds 3 Pro.

**To Reproduce**  
Steps to reproduce the behavior: Go to system -> system information

**Expected behavior**  
move Serial number string to Software version, move software version string to serial number.

**Screenshots**  
![image](https://github.com/user-attachments/assets/2064b6e3-3ebd-40f5-be2c-e24a355fa666)

**Desktop (please complete the following information):**  
 - OS: Windows 11 26100.1297
 
 - Application version: 5.1.0.1-0d8eef8

**Additional context**  
H/W verison, software version, Touch firmware version is not outputting.
Hope to fix it.

**Comment by timschneeb** [comment]
Fixed by commit eb5e8c0ce1a1cf2d998dc934d746d29ffc7db9b0 and a86c273a5962fb12169a2d28a87fb4ec66bf3500

**Comment by backryun** [comment]
I'll try now, thank you for quick response.

**Comment by timschneeb** [comment]
Great :+1: 
The latest commit I just pushed should fix these remaining issues

**Comment by backryun** [comment]
Okay, I'll wait for new commit.
I test on a86c273 version and screenshoted 2nd picture.

**Comment by backryun** [comment]
![image](https://github.com/user-attachments/assets/d0f6309b-b535-4f65-b99a-849e288349e6)
Confimred 46fafcb on fixed issue.
