### ISSUE TITLE
[REQ] The way to enable 'low latency' mode (AKA. Gaming mode)

### ISSUE THREAD

**Issue by flamel7ramond** [timschneeb/GalaxyBudsClient#541]
**Describe the solution you'd like**
just like the samsung wearable apps, integrating the menu to enable gaming mode on homescreen (or somewhere else like sub-menu.

**Comment by neursh** [comment]
The setting is not missing, it just can't be done on PC, as stated in the app. Even the official Galaxy Buds app for Windows doesn't have this.

I think that this feature is only available on Samsung phones using their own audio codec (Samsung Scalable Codec).

![image](https://github.com/user-attachments/assets/4955c3b7-2bec-48cf-a2de-53b935c3415c)

If you're on Windows, try these settings, it might help minimize the latency:
https://www.reddit.com/r/galaxybuds/comments/pa3c4x/galaxy_buds_pro_windows_10_lag_fix/
https://www.reddit.com/r/galaxybuds/comments/b4vx3c/comment/ermyv0y
