### ISSUE TITLE
[REQ]add a function to modify the color displayed by headphones in app?

### ISSUE THREAD

**Issue by small-white-rabbit** [timschneeb/GalaxyBudsClient#579]
Can you add a function to modify the color displayed by headphones in app?

Reason: I lost my right ear. After buying a non-primary color right ear, the color changed. Can I modify this color? So I want to ask if I can add this function?

**Comment by salihefee** [comment]
Is this request for changing the earbud colors independently or both at the same time?

**Comment by small-white-rabbit** [comment]
> 这个要求是单独更改耳塞颜色还是同时更改耳塞颜色？

Binaural, because the colors after recognition are uniform, so it is better to modify them uniformly directly

**Comment by salihefee** [comment]
Created a PR, hopefully this is what you asked for?

**Comment by small-white-rabbit** [comment]
Thank you, brother, for your hard work.
